pub mod account_resource_sync;
pub mod account_workspace_sync;
pub mod agent_environment;
pub mod agent_global_config;
pub(crate) mod agent_runtime;
pub(crate) mod agent_identity_adapter;
pub(crate) mod agent_plugin_bundle;
pub(crate) mod agent_session_adapter;
pub(crate) mod agent_session_identity;
pub mod agent_session_metadata;
pub(crate) mod agent_session_sources;
pub mod agent_session_timeline;
pub mod agent_source_watcher;
pub(crate) mod agent_task_runner;
pub mod agent_version;
pub(crate) mod channel_capability_adapter;
pub mod channels_config;
pub mod codex_account;
pub mod codex_model_catalog;
pub mod config;
pub mod cost_ledger_source_probe;
pub(crate) mod detail_windows;
pub mod device_identity;
pub mod device_sync;
pub mod dsh_control;
pub mod job_runtime;
pub mod lan_sync;
pub mod logging;
pub mod metrics;
pub mod model_catalog;
pub(crate) mod model_input_capabilities;
pub(crate) mod notification_registry;
pub mod opencode_control;
pub(crate) mod pi_session_migration;
#[cfg(test)]
mod plugin_contract;
pub mod plugin_registry;
pub mod power;
pub mod presets;
pub(crate) mod project_workspace_sync;
pub mod proxy;
pub mod rate_limiter;
pub mod runtime_config;
pub mod scrape_console;
#[cfg(desktop)]
pub mod services;
pub mod storage;
pub mod sync;
pub mod usage;
pub mod web;
pub mod webview_profile;
#[cfg(windows)]
pub(crate) mod win_process_job;
pub(crate) mod window_size;
pub(crate) mod window_visibility;

// Re-export commonly used types for headless binary
pub use metrics::Metrics;
pub use proxy::ProxyController;
pub use rate_limiter::RateLimiter;
pub use storage::Storage;
pub use web::create_web_router;
pub use web::WebState;
